//! `MCPGCluster` controller — validates a cluster-coordination
//! backend binding, reports its bindability + blast radius, and (for a
//! `managed` coordinator) PROVISIONS the NATS backend itself.
//!
//! ## Point-at-existing (non-managed) clusters
//!
//! The controller synthesises **no** child objects: a cluster binding is
//! consumed gateway-side (the gateway controller resolves `clusterRef`,
//! renders the backend's `cluster:` block into the gateway config, and
//! folds the cluster's `configHash` into its pod-roll trigger). The job
//! is to resolve `spec.backend` → cdylib id, gate on `spec.pluginRef`
//! readiness when set, compute the config hash + bound-gateway count, and
//! surface a `Ready` condition.
//!
//! ## Managed clusters (`spec.managed`)
//!
//! When a coordinator is managed the controller additionally renders and
//! owns, in the operator namespace: a **NATS StatefulSet** (JetStream
//! file store on a `volumeClaimTemplate`), a **headless + client
//! Service**, a **ConfigMap** (`nats-server.conf`), a **generated
//! coordination Secret** (NATS token and state-encryption key,
//! create-once, plus the CA on the TLS path), and — with
//! `managed.tls.issuerRef` — a cert-manager **Certificate**. These live
//! under a cluster-scoped parent
//! in a namespace, so — matching `controllers::plugin` — they carry no
//! cross-scope owner ref and are pruned by label on deletion. The rendered
//! `cluster:` block (generated by `render_managed_cluster_block`) points
//! bound gateways at the client Service; the gateway controller copies the
//! coordination Secret into each bound gateway's namespace and projects it
//! via `envFrom` (token + state key [+ CA]).

use std::collections::BTreeMap;
use std::sync::Arc;
use std::time::{Duration, Instant};

use base64::Engine as _;
use chrono::Utc;
use futures::StreamExt;
use k8s_openapi::ByteString;
use k8s_openapi::api::apps::v1::StatefulSet;
use k8s_openapi::api::core::v1::{ConfigMap, Secret, Service};
use kube::api::{Api, DeleteParams};
use kube::core::ObjectMeta;
use kube::runtime::controller::{Action, Controller};
use kube::runtime::events::{Event as K8sEvent, EventType};
use kube::runtime::watcher;
use kube::{Resource, ResourceExt};
use mcpg_operator_api::DEFAULT_OPERATOR_NAMESPACE;
use mcpg_operator_api::conditions::{Condition, reasons, types as ctype};
use mcpg_operator_api::v1alpha1::{
    MANAGED_NATS_CA_ENV, MANAGED_NATS_TOKEN_ENV, MANAGED_STATE_KEY_ENV, MCPGCluster,
    MCPGClusterStatus, MCPGGateway, MCPGPlugin, managed_coordination_secret_name,
    managed_nats_config_name, managed_nats_headless_service_name, managed_nats_service_name,
    managed_nats_statefulset_name, managed_nats_tls_secret_name,
};
use rand::{Rng, RngCore};
use sha2::{Digest, Sha256};
use tracing::{error, info, instrument};

use crate::FIELD_MANAGER_PREFIX;
use crate::controllers::gateway::ControllerContext;
use crate::reconcile::{
    OPERATOR_FINALIZER, apply_owned, ensure_finalizer, patch_status, remove_finalizer,
};
use crate::telemetry::ReconcileOutcome;
use crate::templates::edge::Certificate;
use crate::templates::managed_nats::{
    build_nats_certificate, build_nats_client_service, build_nats_configmap,
    build_nats_headless_service, build_nats_statefulset, managed_labels,
};

const FIELD_MANAGER_SUFFIX: &str = "cluster-controller";
const CONTROLLER_NAME: &str = "cluster";

/// Reasons surfaced on `MCPGCluster.status.conditions[Ready]`.
mod cluster_reason {
    /// Backend bindable (plugin verified when `pluginRef` set, or
    /// `single_node`).
    pub const BINDABLE: &str = "Bindable";
    /// `pluginRef` names an `MCPGPlugin` that doesn't exist.
    pub const PLUGIN_NOT_FOUND: &str = "ClusterPluginNotFound";
    /// `pluginRef` plugin exists but isn't `Ready` (unverified /
    /// revoked / still pulling).
    pub const PLUGIN_NOT_READY: &str = "ClusterPluginNotReady";
    /// A managed coordinator is still coming up (StatefulSet not Ready
    /// yet, or the TLS CA has not been issued).
    pub const MANAGED_PROVISIONING: &str = "ManagedCoordinatorProvisioning";
}

#[derive(Debug, thiserror::Error)]
pub enum ReconcileError {
    #[error("status: {0}")]
    Status(#[from] crate::reconcile::StatusError),
    #[error("finalizer: {0}")]
    Finalizer(#[from] crate::reconcile::FinalizerError),
    #[error("apply child: {0}")]
    Apply(#[from] crate::reconcile::ApplyError),
    #[error("kube: {0}")]
    Kube(#[from] kube::Error),
    #[error("missing name on MCPGCluster")]
    MissingName,
}

/// Run the cluster controller until cancelled. Re-reconciles a
/// cluster when a bound `MCPGGateway` changes (blast-radius count) or
/// the referenced `MCPGPlugin` flips readiness.
pub async fn run(ctx: Arc<ControllerContext>) -> anyhow::Result<()> {
    let api: Api<MCPGCluster> = Api::all(ctx.client.clone());

    info!("starting cluster controller");

    Controller::new(api, watcher::Config::default())
        .watches(
            Api::<MCPGGateway>::all(ctx.client.clone()),
            watcher::Config::default(),
            map_gateway_to_clusters,
        )
        .watches(
            Api::<MCPGPlugin>::all(ctx.client.clone()),
            watcher::Config::default(),
            map_plugin_to_clusters,
        )
        .shutdown_on_signal()
        .run(reconcile, error_policy, ctx)
        .for_each(|res| async move {
            match res {
                Ok((obj, _)) => info!(name = %obj.name, "cluster reconciled"),
                Err(err) => error!(error = ?err, "cluster reconcile failed"),
            }
        })
        .await;

    Ok(())
}

/// A gateway change re-reconciles the cluster it binds (so
/// `boundGateways` stays current). Gateways with no `clusterRef`
/// map to nothing.
fn map_gateway_to_clusters(
    gw: MCPGGateway,
) -> Vec<kube::runtime::reflector::ObjectRef<MCPGCluster>> {
    gw.spec
        .cluster_ref
        .as_ref()
        .map(|r| vec![kube::runtime::reflector::ObjectRef::new(&r.name)])
        .unwrap_or_default()
}

/// An `MCPGPlugin` readiness flip re-reconciles any cluster that
/// pins it via `pluginRef`. We can't cheaply reverse-index without
/// listing, so we re-reconcile by matching name at reconcile time;
/// here we conservatively map the plugin to a cluster of the same
/// name (the common convention) — the reconcile re-checks the real
/// `pluginRef` regardless, so a missed edge just waits for resync.
fn map_plugin_to_clusters(
    plugin: MCPGPlugin,
) -> Vec<kube::runtime::reflector::ObjectRef<MCPGCluster>> {
    vec![kube::runtime::reflector::ObjectRef::new(&plugin.name_any())]
}

#[instrument(
    skip_all,
    fields(name = %obj.name_any(), generation = obj.metadata.generation.unwrap_or(0))
)]
async fn reconcile(
    obj: Arc<MCPGCluster>,
    ctx: Arc<ControllerContext>,
) -> Result<Action, ReconcileError> {
    let started = Instant::now();
    let metrics = ctx.metrics.operator_metrics().clone();
    let result = reconcile_inner(obj, ctx).await;
    let outcome = match &result {
        Ok((_, o)) => *o,
        Err(ReconcileError::MissingName) => ReconcileOutcome::PermanentError,
        Err(_) => ReconcileOutcome::TransientError,
    };
    metrics.observe_reconcile(CONTROLLER_NAME, outcome, started.elapsed().as_secs_f64());
    result.map(|(action, _)| action)
}

async fn reconcile_inner(
    obj: Arc<MCPGCluster>,
    ctx: Arc<ControllerContext>,
) -> Result<(Action, ReconcileOutcome), ReconcileError> {
    let name = obj
        .metadata
        .name
        .clone()
        .ok_or(ReconcileError::MissingName)?;
    let observed_generation = obj.metadata.generation.unwrap_or(0);
    let cluster_api: Api<MCPGCluster> = Api::all(ctx.client.clone());

    // Deletion branch — a managed cluster owns children (with no
    // cross-scope owner ref), so prune them by label before releasing the
    // finalizer. Non-managed clusters synthesise nothing; bound gateways
    // fall back to keep-last-good on their own next reconcile.
    if obj.metadata.deletion_timestamp.is_some() {
        info!(name = %name, "cluster deletion in progress; releasing finalizer");
        if obj.spec.managed.is_some() {
            prune_managed_children(&ctx.client, DEFAULT_OPERATOR_NAMESPACE, &name).await;
        }
        remove_finalizer(&cluster_api, &name, OPERATOR_FINALIZER).await?;
        return Ok((Action::await_change(), ReconcileOutcome::Success));
    }
    ensure_finalizer(&cluster_api, &name, obj.as_ref(), OPERATOR_FINALIZER).await?;

    // A managed coordinator is implicitly NATS regardless of the (admission-
    // rejected) `backend` field, so every readiness / bindability check
    // keys off the effective backend.
    let backend = obj.spec.effective_backend();
    let plugin_id = backend.plugin_id().map(str::to_owned);

    // Rendered config block + its hash (the gateway pod-roll trigger).
    // Managed-aware: the generated NATS block needs the cluster name +
    // operator namespace to form the Service FQDN.
    let config_block = obj
        .spec
        .render_cluster_block_with(&name, DEFAULT_OPERATOR_NAMESPACE);
    let config_hash = {
        let json = serde_json::to_string(&config_block).unwrap_or_default();
        let mut h = Sha256::new();
        h.update(json.as_bytes());
        hex::encode(h.finalize())
    };

    // Managed provisioning: render + own the NATS backend, and gate the
    // cluster's readiness on it. `None` for a point-at-existing cluster.
    let managed = if obj.spec.managed.is_some() {
        Some(reconcile_managed(&ctx, obj.as_ref(), &name).await?)
    } else {
        None
    };

    // Bindability gate. A managed coordinator must finish provisioning; a
    // `pluginRef` (managed or not) must resolve to a Ready plugin.
    let (ready, reason, message) =
        classify_readiness(&ctx, obj.as_ref(), backend, managed.as_ref()).await?;

    // Blast radius: how many gateways bind this cluster.
    let bound_gateways = count_bound_gateways(&ctx.client, &name).await?;

    // Status.
    let mut conditions = obj
        .status
        .as_ref()
        .map(|s| s.conditions.clone())
        .unwrap_or_default();
    mcpg_operator_api::conditions::set_condition(
        &mut conditions,
        Condition::new(
            ctype::READY,
            if ready { "True" } else { "False" },
            if ready { reasons::RECONCILED } else { reason },
            message.clone(),
            Some(observed_generation),
        ),
    );

    let status = MCPGClusterStatus {
        conditions,
        observed_generation: Some(observed_generation),
        plugin_id: plugin_id.clone(),
        bound_gateways: Some(bound_gateways),
        config_hash: Some(config_hash),
        managed_ready: managed.as_ref().map(|m| m.ready),
        nats_ready_replicas: managed.as_ref().map(|m| m.nats_ready_replicas),
        coordination_secret: managed.as_ref().map(|m| m.secret_name.clone()),
        last_reconcile_time: Some(Utc::now()),
    };

    let fm = format!("{FIELD_MANAGER_PREFIX}/{FIELD_MANAGER_SUFFIX}");
    if let Err(e) = patch_status(&cluster_api, &name, &status, &fm).await {
        tracing::warn!(error = ?e, "cluster: status patch failed");
    }

    // Emit an Event on the not-bindable path so `kubectl describe`
    // shows why a gateway binding is stuck.
    if !ready {
        let evt = K8sEvent {
            type_: EventType::Warning,
            reason: reason.to_owned(),
            note: Some(message.clone()),
            action: "Bind".to_owned(),
            secondary: None,
        };
        let _ = ctx
            .recorders
            .cluster
            .publish(&evt, &obj.object_ref(&()))
            .await;
    }

    if ready {
        Ok((
            Action::requeue(jittered_resync(ctx.config.resync_interval_secs)),
            ReconcileOutcome::Success,
        ))
    } else {
        // Not ready. For a managed coordinator still coming up, poll on a
        // short interval so the cluster flips Ready (and the gateway
        // admission guard unblocks) promptly — the controller watches no
        // StatefulSet. For a plugin-pending non-managed cluster the
        // MCPGPlugin `.watches()` nudge is the fast path, with the resync
        // requeue as backstop.
        let delay = if managed.is_some() {
            Duration::from_secs(15)
        } else {
            jittered_resync(ctx.config.resync_interval_secs)
        };
        Ok((Action::requeue(delay), ReconcileOutcome::DependencyPending))
    }
}

/// Periodic resync interval, jittered ±20% so a fleet of clusters
/// doesn't thundering-herd the apiserver on the same tick. Mirrors
/// the gateway controller's helper.
fn jittered_resync(base_secs: u64) -> Duration {
    let base = base_secs as f64;
    let jitter_factor = 0.8 + rand::thread_rng().gen_range(0.0..0.4);
    Duration::from_secs_f64(base * jitter_factor)
}

/// True when an `MCPGPlugin` has a `Ready=True` condition and isn't
/// flagged revoked.
fn plugin_is_ready(p: &MCPGPlugin) -> bool {
    let Some(status) = p.status.as_ref() else {
        return false;
    };
    if status.revoked_by_sha == Some(true) {
        return false;
    }
    status
        .conditions
        .iter()
        .any(|c| c.r#type == ctype::READY && c.status == "True")
}

/// Count `MCPGGateway`s (cluster-wide) whose `clusterRef.name`
/// matches this cluster.
async fn count_bound_gateways(
    client: &kube::Client,
    cluster_name: &str,
) -> Result<i64, ReconcileError> {
    let api: Api<MCPGGateway> = Api::all(client.clone());
    let gateways = api.list(&Default::default()).await?;
    let count = gateways
        .items
        .iter()
        .filter(|g| {
            g.spec
                .cluster_ref
                .as_ref()
                .is_some_and(|r| r.name == cluster_name)
        })
        .count();
    Ok(count as i64)
}

/// Outcome of provisioning a managed NATS coordinator this reconcile.
struct ManagedOutcome {
    /// Coordinator is fully up: StatefulSet has its ready replica and, on
    /// the TLS path, the CA has been issued + folded into the Secret.
    ready: bool,
    /// Ready replicas of the provisioned NATS StatefulSet.
    nats_ready_replicas: i32,
    /// Generated coordination Secret name (operator namespace).
    secret_name: String,
    /// Human-readable readiness detail for the `Ready` condition.
    message: String,
}

/// Provision (SSA) the managed NATS backend and report its readiness. Runs
/// only when `spec.managed` is set. Renders into the operator namespace:
/// Certificate (TLS) → coordination Secret (create-once) → ConfigMap +
/// Services + StatefulSet.
async fn reconcile_managed(
    ctx: &Arc<ControllerContext>,
    obj: &MCPGCluster,
    name: &str,
) -> Result<ManagedOutcome, ReconcileError> {
    let ns = DEFAULT_OPERATOR_NAMESPACE;
    let fm = format!("{FIELD_MANAGER_PREFIX}/{FIELD_MANAGER_SUFFIX}");
    let tls_enabled = obj.spec.managed_tls_enabled();
    let replicas = obj.spec.managed_nats_replicas().unwrap_or(1);

    // Surface the degraded / capped shapes as Warning events.
    if !tls_enabled {
        emit_warning(
            ctx,
            obj,
            "PlaintextCoordinator",
            "managed NATS runs plaintext in-cluster (no managed.tls.issuerRef); shared \
             coordinator state crosses the pod network unencrypted at the transport — set \
             managed.tls.issuerRef for in-cluster TLS. State-at-rest stays sealed by the \
             generated state-encryption key regardless.",
        )
        .await;
    }
    if obj.spec.managed_replicas_capped() {
        emit_warning(
            ctx,
            obj,
            "ReplicasCapped",
            "managed NATS renders single-node JetStream; managed.replicas > 1 is capped at 1 \
             (clustered-NATS quorum config is not rendered in this version).",
        )
        .await;
    }

    // 1. Certificate first (TLS) so cert-manager begins issuing before the
    //    StatefulSet needs to mount the server cert.
    if tls_enabled
        && let Some(issuer) = obj
            .spec
            .managed
            .as_ref()
            .and_then(|m| m.tls.as_ref())
            .and_then(|t| t.issuer_ref.as_ref())
    {
        let cert = build_nats_certificate(obj, ns, issuer);
        let cert_api: Api<Certificate> = Api::namespaced(ctx.client.clone(), ns);
        apply_owned(&cert_api, &cert, &fm).await?;
    }

    // 2. Read the issued CA (TLS) so it can ride the coordination Secret to
    //    bound gateways (they trust it as the nats plugin's root).
    let ca = if tls_enabled {
        read_ca_cert(&ctx.client, ns, &managed_nats_tls_secret_name(name)).await
    } else {
        None
    };
    let ca_available = !tls_enabled || ca.is_some();

    // 3. Coordination Secret — create-once token + state key; the CA (TLS)
    //    is synced from the issued cert each reconcile.
    let secret_name = ensure_coordination_secret(&ctx.client, ns, name, ca.as_deref(), &fm).await?;

    // 4. ConfigMap + Services + StatefulSet.
    let cm = build_nats_configmap(obj, ns, tls_enabled);
    let headless = build_nats_headless_service(obj, ns);
    let client = build_nats_client_service(obj, ns);
    let statefulset = build_nats_statefulset(obj, ns, replicas, tls_enabled);
    let cm_api: Api<ConfigMap> = Api::namespaced(ctx.client.clone(), ns);
    let svc_api: Api<Service> = Api::namespaced(ctx.client.clone(), ns);
    let ss_api: Api<StatefulSet> = Api::namespaced(ctx.client.clone(), ns);
    apply_owned(&cm_api, &cm, &fm).await?;
    apply_owned(&svc_api, &headless, &fm).await?;
    apply_owned(&svc_api, &client, &fm).await?;
    let applied = apply_owned(&ss_api, &statefulset, &fm).await?;

    // 5. Readiness: the StatefulSet has its ready replica, and (TLS) the CA
    //    has been issued.
    let nats_ready = applied
        .status
        .as_ref()
        .and_then(|s| s.ready_replicas)
        .unwrap_or(0);
    let ready = nats_ready >= 1 && ca_available;
    let message = if ready {
        format!(
            "managed NATS coordinator ready ({nats_ready}/{replicas}, {})",
            if tls_enabled { "TLS" } else { "plaintext" }
        )
    } else if !ca_available {
        "managed NATS TLS certificate not issued yet (waiting on cert-manager)".to_owned()
    } else {
        format!("managed NATS StatefulSet not ready yet ({nats_ready}/{replicas})")
    };

    Ok(ManagedOutcome {
        ready,
        nats_ready_replicas: nats_ready,
        secret_name,
        message,
    })
}

/// Bindability verdict: `(ready, reason, message)`. A managed coordinator
/// must finish provisioning; a `pluginRef` (managed or not) must resolve to
/// a Ready, non-revoked plugin.
async fn classify_readiness(
    ctx: &Arc<ControllerContext>,
    obj: &MCPGCluster,
    backend: mcpg_operator_api::v1alpha1::ClusterBackend,
    managed: Option<&ManagedOutcome>,
) -> Result<(bool, &'static str, String), ReconcileError> {
    if let Some(m) = managed
        && !m.ready
    {
        return Ok((
            false,
            cluster_reason::MANAGED_PROVISIONING,
            m.message.clone(),
        ));
    }

    match &obj.spec.plugin_ref {
        Some(plugin_ref) => {
            let plugin_api: Api<MCPGPlugin> = Api::all(ctx.client.clone());
            match plugin_api.get_opt(&plugin_ref.name).await? {
                None => Ok((
                    false,
                    cluster_reason::PLUGIN_NOT_FOUND,
                    format!("clusterPlugin '{}' not found", plugin_ref.name),
                )),
                Some(p) if plugin_is_ready(&p) => Ok((
                    true,
                    cluster_reason::BINDABLE,
                    format!(
                        "backend '{}' bindable via verified plugin '{}'",
                        backend.config_kind(),
                        plugin_ref.name
                    ),
                )),
                Some(_) => Ok((
                    false,
                    cluster_reason::PLUGIN_NOT_READY,
                    format!(
                        "clusterPlugin '{}' is not Ready (unverified / revoked / pulling)",
                        plugin_ref.name
                    ),
                )),
            }
        }
        // No pluginRef: managed reports its own readiness; single_node
        // needs no plugin; an external backend trusts the gateway's
        // pluginSetRef to carry the cdylib. Bindable either way.
        None => {
            let message = if let Some(m) = managed {
                m.message.clone()
            } else if backend.is_single_node() {
                "in-process single_node coordinator".to_owned()
            } else {
                format!(
                    "backend '{}' bindable (cdylib supplied via gateway pluginSetRef)",
                    backend.config_kind()
                )
            };
            Ok((true, cluster_reason::BINDABLE, message))
        }
    }
}

/// Ensure the generated coordination Secret exists in the operator
/// namespace. The NATS token and state-encryption key are **create-once**
/// (never overwritten once present — a rotation would orphan sealed state);
/// the CA (TLS) tracks the issued cert. Returns the Secret name.
async fn ensure_coordination_secret(
    client: &kube::Client,
    namespace: &str,
    cluster_name: &str,
    ca: Option<&str>,
    field_manager: &str,
) -> Result<String, ReconcileError> {
    let secret_name = managed_coordination_secret_name(cluster_name);
    let api: Api<Secret> = Api::namespaced(client.clone(), namespace);

    // Preserve any existing key material so re-reconcile never rotates it.
    let existing = api
        .get_opt(&secret_name)
        .await?
        .and_then(|s| s.data)
        .unwrap_or_default();
    let data = merge_coordination_data(existing, ca);

    let secret = Secret {
        metadata: ObjectMeta {
            name: Some(secret_name.clone()),
            namespace: Some(namespace.to_owned()),
            labels: Some(managed_labels(cluster_name)),
            ..Default::default()
        },
        type_: Some("Opaque".to_owned()),
        data: Some(data),
        ..Default::default()
    };
    apply_owned(&api, &secret, field_manager).await?;
    Ok(secret_name)
}

/// Read the CA PEM from a cert-manager-issued TLS Secret (`ca.crt`).
/// `None` until the Secret exists (cert not yet issued).
async fn read_ca_cert(
    client: &kube::Client,
    namespace: &str,
    tls_secret_name: &str,
) -> Option<String> {
    let api: Api<Secret> = Api::namespaced(client.clone(), namespace);
    let secret = api.get_opt(tls_secret_name).await.ok().flatten()?;
    let ca = secret.data?.get("ca.crt")?.0.clone();
    String::from_utf8(ca).ok().filter(|p| !p.trim().is_empty())
}

/// Create-once merge of the coordination Secret's data: the NATS token and
/// state-encryption key are minted only when absent (never overwritten — a
/// rotation would orphan every sealed record), while the CA tracks the
/// issued cert (inserted when present, dropped when TLS is off). Pure so the
/// create-once invariant is unit-testable without an apiserver.
fn merge_coordination_data(
    existing: BTreeMap<String, ByteString>,
    ca: Option<&str>,
) -> BTreeMap<String, ByteString> {
    let mut data = existing;
    data.entry(MANAGED_NATS_TOKEN_ENV.to_owned())
        .or_insert_with(|| ByteString(gen_url_safe_key(32).into_bytes()));
    data.entry(MANAGED_STATE_KEY_ENV.to_owned())
        .or_insert_with(|| ByteString(gen_url_safe_key(32).into_bytes()));
    match ca {
        Some(pem) => {
            data.insert(
                MANAGED_NATS_CA_ENV.to_owned(),
                ByteString(pem.as_bytes().to_vec()),
            );
        }
        None => {
            data.remove(MANAGED_NATS_CA_ENV);
        }
    }
    data
}

/// 32-byte (default) random value as URL-safe unpadded base64 — the
/// alphabet the gateway's state-key + token loaders accept. A 32-byte
/// source decodes back to exactly 32 bytes (the state-key requirement).
fn gen_url_safe_key(bytes: usize) -> String {
    let mut buf = vec![0u8; bytes];
    rand::thread_rng().fill_bytes(&mut buf);
    base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(&buf)
}

/// Best-effort teardown of a managed coordinator's children on cluster
/// deletion (they carry no cross-scope owner ref). PVCs from the
/// StatefulSet's `volumeClaimTemplate` are intentionally RETAINED (the
/// StatefulSet default) so coordinator state survives a re-create.
async fn prune_managed_children(client: &kube::Client, namespace: &str, cluster_name: &str) {
    let dp = DeleteParams::default();
    let ss: Api<StatefulSet> = Api::namespaced(client.clone(), namespace);
    let _ = ss
        .delete(&managed_nats_statefulset_name(cluster_name), &dp)
        .await;
    let svc: Api<Service> = Api::namespaced(client.clone(), namespace);
    let _ = svc
        .delete(&managed_nats_service_name(cluster_name), &dp)
        .await;
    let _ = svc
        .delete(&managed_nats_headless_service_name(cluster_name), &dp)
        .await;
    let cm: Api<ConfigMap> = Api::namespaced(client.clone(), namespace);
    let _ = cm
        .delete(&managed_nats_config_name(cluster_name), &dp)
        .await;
    let sec: Api<Secret> = Api::namespaced(client.clone(), namespace);
    let _ = sec
        .delete(&managed_coordination_secret_name(cluster_name), &dp)
        .await;
    // The Certificate owns its TLS Secret (GC cascades); delete it and the
    // Secret best-effort (404 is the common case).
    let cert: Api<Certificate> = Api::namespaced(client.clone(), namespace);
    let _ = cert
        .delete(&managed_nats_tls_secret_name(cluster_name), &dp)
        .await;
    let _ = sec
        .delete(&managed_nats_tls_secret_name(cluster_name), &dp)
        .await;
}

/// Publish a Warning event against the `MCPGCluster` (best-effort).
async fn emit_warning(ctx: &Arc<ControllerContext>, obj: &MCPGCluster, reason: &str, note: &str) {
    let evt = K8sEvent {
        type_: EventType::Warning,
        reason: reason.to_owned(),
        note: Some(note.to_owned()),
        action: "Provision".to_owned(),
        secondary: None,
    };
    let _ = ctx
        .recorders
        .cluster
        .publish(&evt, &obj.object_ref(&()))
        .await;
}

fn error_policy(
    obj: Arc<MCPGCluster>,
    err: &ReconcileError,
    ctx: Arc<ControllerContext>,
) -> Action {
    match err {
        ReconcileError::MissingName => Action::await_change(),
        _ => {
            let key = crate::backoff::resource_key(CONTROLLER_NAME, "", &obj.name_any());
            let count = ctx.backoff.record_error(&key);
            let delay = ctx.backoff.duration_for(&key);
            tracing::warn!(
                key = %key,
                consecutive_errors = count,
                requeue_secs = delay.as_secs(),
                error = ?err,
                "cluster: reconcile error; backing off"
            );
            Action::requeue(delay)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use kube::core::ObjectMeta;
    use mcpg_operator_api::v1alpha1::{ClusterBackend, MCPGClusterSpec};

    fn cluster(spec: MCPGClusterSpec) -> MCPGCluster {
        MCPGCluster {
            metadata: ObjectMeta {
                name: Some("prod-cluster".into()),
                ..Default::default()
            },
            spec,
            status: None,
        }
    }

    #[test]
    fn single_node_renders_kind_only() {
        let c = cluster(MCPGClusterSpec {
            backend: ClusterBackend::SingleNode,
            ..Default::default()
        });
        let block = c.spec.render_cluster_block();
        assert_eq!(block["kind"], "single_node");
    }

    #[test]
    fn plugin_ready_requires_ready_condition_and_not_revoked() {
        use mcpg_operator_api::v1alpha1::{MCPGPlugin, MCPGPluginSpec};
        let mk = |conds: Vec<Condition>, revoked: Option<bool>| MCPGPlugin {
            metadata: ObjectMeta {
                name: Some("cluster-redis".into()),
                ..Default::default()
            },
            spec: MCPGPluginSpec {
                plugin_id: "dev.mcpg.cluster.redis".into(),
                version: "1.0.0".into(),
                plugin_class: "cluster".into(),
                ..Default::default()
            },
            status: Some(mcpg_operator_api::v1alpha1::MCPGPluginStatus {
                conditions: conds,
                revoked_by_sha: revoked,
                ..Default::default()
            }),
        };
        let ready = Condition::new(ctype::READY, "True", reasons::RECONCILED, "ok", Some(1));
        let not_ready = Condition::new(ctype::READY, "False", "Pulling", "x", Some(1));
        assert!(plugin_is_ready(&mk(vec![ready.clone()], None)));
        assert!(!plugin_is_ready(&mk(vec![not_ready], None)));
        // Ready but revoked → not bindable.
        assert!(!plugin_is_ready(&mk(vec![ready], Some(true))));
        // No status → not ready.
        assert!(!plugin_is_ready(&MCPGPlugin {
            metadata: ObjectMeta::default(),
            spec: MCPGPluginSpec::default(),
            status: None,
        }));
    }

    #[test]
    fn gateway_with_no_clusterref_maps_to_nothing() {
        let gw = MCPGGateway {
            metadata: ObjectMeta {
                name: Some("g".into()),
                namespace: Some("ns".into()),
                ..Default::default()
            },
            spec: Default::default(),
            status: None,
        };
        assert!(map_gateway_to_clusters(gw).is_empty());
    }

    // ── Managed coordination Secret (create-once) ──────────────

    fn bytes(m: &BTreeMap<String, ByteString>, k: &str) -> Vec<u8> {
        m.get(k).expect("key present").0.clone()
    }

    #[test]
    fn coordination_data_generates_token_and_state_key() {
        let data = merge_coordination_data(BTreeMap::new(), None);
        let token = bytes(&data, MANAGED_NATS_TOKEN_ENV);
        let state = bytes(&data, MANAGED_STATE_KEY_ENV);
        assert!(!token.is_empty());
        assert!(!state.is_empty());
        assert_ne!(token, state, "token and state key must be distinct");
        // No CA on the plaintext path.
        assert!(!data.contains_key(MANAGED_NATS_CA_ENV));
        // State key decodes back to exactly 32 bytes (the gateway loader's
        // requirement) — 32 random bytes as URL-safe base64.
        let decoded = base64::engine::general_purpose::URL_SAFE_NO_PAD
            .decode(&state)
            .expect("state key is url-safe base64");
        assert_eq!(decoded.len(), 32);
    }

    #[test]
    fn coordination_data_is_create_once_on_re_reconcile() {
        // First reconcile mints the material…
        let first = merge_coordination_data(BTreeMap::new(), None);
        let token = bytes(&first, MANAGED_NATS_TOKEN_ENV);
        let state = bytes(&first, MANAGED_STATE_KEY_ENV);
        // …a second reconcile with the existing data preserves it verbatim
        // (a rotation would orphan every sealed record).
        let second = merge_coordination_data(first.clone(), None);
        assert_eq!(bytes(&second, MANAGED_NATS_TOKEN_ENV), token);
        assert_eq!(bytes(&second, MANAGED_STATE_KEY_ENV), state);
    }

    #[test]
    fn coordination_data_syncs_and_drops_ca() {
        // TLS path: CA folded in, token/state preserved.
        let base = merge_coordination_data(BTreeMap::new(), None);
        let with_ca =
            merge_coordination_data(base.clone(), Some("-----BEGIN CERTIFICATE-----\nX\n"));
        assert_eq!(
            bytes(&with_ca, MANAGED_NATS_CA_ENV),
            b"-----BEGIN CERTIFICATE-----\nX\n".to_vec()
        );
        assert_eq!(
            bytes(&with_ca, MANAGED_NATS_TOKEN_ENV),
            bytes(&base, MANAGED_NATS_TOKEN_ENV),
            "CA sync must not rotate the token"
        );
        // Turning TLS off removes the CA (but keeps token/state).
        let without_ca = merge_coordination_data(with_ca, None);
        assert!(!without_ca.contains_key(MANAGED_NATS_CA_ENV));
        assert_eq!(
            bytes(&without_ca, MANAGED_NATS_TOKEN_ENV),
            bytes(&base, MANAGED_NATS_TOKEN_ENV)
        );
    }

    #[test]
    fn generated_keys_are_url_safe_unpadded() {
        let k = gen_url_safe_key(32);
        assert_eq!(k.len(), 43, "32 bytes → 43 unpadded base64url chars");
        assert!(!k.contains('='), "unpadded");
        assert!(
            k.chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_'),
            "url-safe alphabet only: {k}"
        );
    }
}
